**Cheatsheet for NumPy Emath Module**
================================

### arccos
#### Function Description
Computes the trigonometric inverse cosine, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The inverse cosine of each element in `x`.

#### Examples
```python
import numpy as np

x = np.array([-1, 0, 1])
print(np.arccos(x))  # Output: [ 3.14159265  1.57079633  0.        ]
```

In [3]:
# Interactive Example
import numpy as np
x = np.array([-1, 0, 1])
result = np.arccos(x)
result

array([3.14159265, 1.57079633, 0.        ])

### arccosh
#### Function Description
Computes the inverse hyperbolic cosine, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The inverse hyperbolic cosine of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([1, 2, 3])
print(np.arccosh(x))  # Output: [ 0.         1.3169579  1.76274717]
```

In [6]:
# Interactive Example
import numpy as np
x = np.array([1, 2, 3])
result = np.arccosh(x)
result

array([0.        , 1.3169579 , 1.76274717])

### arcsin
#### Function Description
Computes the trigonometric inverse sine, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The inverse sine of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([-1, 0, 1])
print(np.arcsin(x))  # Output: [-1.57079633  0.         1.57079633]
```

In [7]:
# Interactive Example
import numpy as np
x = np.array([-1, 0, 1])
result = np.arcsin(x)
result

array([-1.57079633,  0.        ,  1.57079633])

### arcsinh
#### Function Description
Computes the inverse hyperbolic sine, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The inverse hyperbolic sine of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([-1, 0, 1])
print(np.arcsinh(x))  # Output: [-0.88137358  0.         0.88137358]
```

In [13]:
# Interactive Example
import numpy as np
x = np.array([-1, 0, 1])
result = np.arcsinh(x)
result

array([-0.88137359,  0.        ,  0.88137359])

### arctan
#### Function Description
Computes the trigonometric inverse tangent, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The inverse tangent of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([-1, 0, 1])
print(np.arctan(x))  # Output: [-0.78539816  0.         0.78539816]
```

In [12]:
# Interactive Example
import numpy as np
x = np.array([-1, 0, 1])
result = np.arctan(x)
result

array([-0.78539816,  0.        ,  0.78539816])

### arctanh
#### Function Description
Computes the inverse hyperbolic tangent, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The inverse hyperbolic tangent of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([-0.5, 0, 0.5])
print(np.arctanh(x))  # Output: [-0.54930614  0.         0.54930614]
```

In [14]:
# Interactive Example
import numpy as np
x = np.array([-0.5, 0, 0.5])
result = np.arctanh(x)
result

array([-0.54930614,  0.        ,  0.54930614])

### cos
#### Function Description
Computes the trigonometric cosine, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The cosine of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([0, np.pi/2, np.pi])
print(np.cos(x))  # Output: [ 1.         6.12323399e-17 -1.        ]
```

In [15]:
# Interactive Example
import numpy as np
x = np.array([0, np.pi/2, np.pi])
result = np.cos(x)
result

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

### cosh
#### Function Description
Computes the hyperbolic cosine, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The hyperbolic cosine of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([0, 1, 2])
print(np.cosh(x))  # Output: [ 1.         1.54308063  3.76219569]
```

In [16]:
# Interactive Example
import numpy as np
x = np.array([0, 1, 2])
result = np.cosh(x)
result

array([1.        , 1.54308063, 3.76219569])

### exp
#### Function Description
Computes the exponential, element-wise.

#### Parameters
* x: array_like
	+ Input array.

#### Returns
* out: ndarray
	+ The exponential of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([0, 1, 2])
print(np.exp(x))  # Output: [ 1.         2.71828183  7.3890561 ]
```

In [17]:
# Interactive Example
import numpy as np
x = np.array([0, 1, 2])
result = np.exp(x)
result

array([1.        , 2.71828183, 7.3890561 ])

### log
#### Function Description
Compute the natural logarithm, element-wise.

#### Parameters
* `x` : array_like - Input values.

#### Returns
* `out` : ndarray - The natural logarithm of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([1, 2, 3])
np.log(x)  # array([0.        , 0.69314718, 1.09861229])
```

In [18]:
# Interactive Example
import numpy as np
x = np.array([1, 2, 3])
result = np.log(x)
result

array([0.        , 0.69314718, 1.09861229])

### log10
#### Function Description
Compute the base-10 logarithm, element-wise.

##### Parameters
* `x` : array_like - Input values.

#### Returns
* `out` : ndarray - The base-10 logarithm of each element in `x`.

#### Examples
```python
import numpy as np
x = np.array([1, 10, 100])
np.log10(x)  # array([0.        , 1.        , 2.        ])
```

In [19]:
# Interactive Example
import numpy as np
x = np.array([1, 10, 100])
result = np.log10(x)
result

array([0., 1., 2.])

### sin()
#### Function Description
Computes the trigonometric sine of an array element-wise.

#### Parameters
* `x`: Input array.

#### Returns
* `out`: Output array with same shape as `x`.

#### Examples
```python
import numpy as np
x = np.array([0, np.pi/2, np.pi])
print(np.sin(x))  # Output: [ 0.          1.          -0.        ]
```

In [20]:
# Interactive Example
import numpy as np
x = np.array([0, np.pi/2, np.pi])
result = np.sin(x)
result

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### sinh()
#### Function Description
Computes the hyperbolic sine of an array element-wise.

#### Parameters
* `x`: Input array.

#### Returns
* `out`: Output array with same shape as `x`.

#### Examples
```python
import numpy as np
x = np.array([0, 1, 2])
print(np.sinh(x))  # Output: [ 0.         1.17520119  3.62686041]
```

In [ ]:
# Interactive Example
import numpy as np
x = np.array([0, 1, 2])
result = np.sinh(x)
result

### sqrt()
#### Function Description
Computes the element-wise square root of an array.

#### Parameters
* `x`: Input array.

#### Returns
* `out`: Output array with same shape as `x`.

#### Examples
```python
import numpy as np
x = np.array([1, 4, 9])
print(np.sqrt(x))  # Output: [1. 2. 3.]
```

In [21]:
# Interactive Example
import numpy as np
x = np.array([1, 4, 9])
result = np.sqrt(x)
result

array([1., 2., 3.])

### tan()
#### Function Description
Computes the trigonometric tangent of an array element-wise.

#### Parameters
* `x`: Input array.

#### Returns
* `out`: Output array with same shape as `x`.

#### Examples
```python
import numpy as np
x = np.array([0, np.pi/4, np.pi/2])
print(np.tan(x))  # Output: [ 0.         1.         -inf]
```

In [22]:
# Interactive Example
import numpy as np
x = np.array([0, np.pi/4, np.pi/2])
result = np.tan(x)
result

array([0.00000000e+00, 1.00000000e+00, 1.63312394e+16])

### tanh()
##### Function Description
Computes the hyperbolic tangent of an array element-wise.

#### Parameters
* `x`: Input array.

#### Returns
* `out`: Output array with same shape as `x`.

#### Examples
```python
import numpy as np
x = np.array([0, 1, 2])
print(np.tanh(x))  # Output: [ 0.         0.76159416  0.96402758]
```

In [23]:
# Interactive Example
import numpy as np
x = np.array([0, 1, 2])
result = np.tanh(x)
result

array([0.        , 0.76159416, 0.96402758])