**NumPy Cheatsheet for FFT Module**
=============================

### **fft.fftfreq**
---------------------

#### Function Description
Return the frequencies corresponding to the components of the FFT.

#### Parameters

* `n`: int, number of points
* `d`: float, sample spacing (default 1.0)

#### Returns

* `f`: ndarray, frequencies

#### Examples
```python
import numpy as np
f = np.fft.fftfreq(8)
print(f)
```

In [3]:
#Interactive Example
import numpy as np
f = np.fft.fftfreq(8)
print(f)

[ 0.     0.125  0.25   0.375 -0.5   -0.375 -0.25  -0.125]


### **fft.fftshift**
---------------------

#### Function Description
Shift the zero-frequency component to the center of the spectrum.

#### Parameters

* `x`: array_like, input array
* `axes`: int or tuple, axes to shift (default None)

#### Returns

* `x`: ndarray, shifted array

#### Examples
```python
import numpy as np
x = np.fft.ifftshift([0, 1, 2, 3, 4, -5, -4, -3, -2, -1])
print(x)
```

In [4]:
#Interactive Example
import numpy as np
x = np.fft.ifftshift([0, 1, 2, 3, 4, -5, -4, -3, -2, -1])
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]


### **fft.ifftshift**
---------------------

#### Function Description
Inverse of `fftshift`.

#### Parameters

* `x`: array_like, input array
* `axes`: int or tuple, axes to shift (default None)

#### Returns

* `x`: ndarray, shifted array

#### Examples
```python
import numpy as np
x = np.fft.ifftshift([0, 1, 2, 3, 4, -5, -4, -3, -2, -1])
print(x)
```

In [5]:
#Interactive Example
import numpy as np
x = np.fft.ifftshift([0, 1, 2, 3, 4, -5, -4, -3, -2, -1])
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]


### **fft.fft**
----------------

#### Function Description
Compute the one-dimensional discrete Fourier Transform.

#### Parameters

* `x`: array_like, input array
* `n`: int, length of the transform (default None)
* `axis`: int, axis along which to compute the transform (default -1)

#### Returns

* `out`: ndarray, complex transform

#### Examples
```python
import numpy as np
x = np.array([0, 1, 2, 3])
X = np.fft.fft(x)
print(X)
```

In [6]:
#Interactive Example
import numpy as np
x = np.array([0, 1, 2, 3])
X = np.fft.fft(x)
print(X)

[ 6.+0.j -2.+2.j -2.+0.j -2.-2.j]


### **fft.ifft**
-----------------

#### Function Description
Compute the inverse one-dimensional discrete Fourier Transform.

#### Parameters

* `x`: array_like, input array
* `n`: int, length of the transform (default None)
* `axis`: int, axis along which to compute the transform (default -1)

#### Returns

* `out`: ndarray, real-value inverse transform

#### Examples
```python
import numpy as np
X = np.array([0, 1, 2, 3])
x = np.fft.ifft(X)
print(x)
```

In [7]:
#Interactive Example
import numpy as np
X = np.array([0, 1, 2, 3])
x = np.fft.ifft(X)
print(x)

[ 1.5+0.j  -0.5-0.5j -0.5+0.j  -0.5+0.5j]


### **fft.fft2**
-----------------

#### Function Description
Compute the two-dimensional discrete Fourier Transform.

#### Parameters

* `x`: array_like, input array
* `s`: int or tuple, shape of the output (default None)
* `axes`: int or tuple, axes along which to compute the transform (default (-2, -1))

#### Returns

* `out`: ndarray, complex transform

#### Examples
```python
import numpy as np
x = np.random.rand(4, 4)
X = np.fft.fft2(x)
print(X)
```

In [8]:
#Interactive Example
import numpy as np
x = np.random.rand(4, 4)
X = np.fft.fft2(x)
print(X)

[[ 7.18440424+0.j         -0.28588999+0.92860837j  0.9317531 +0.j
  -0.28588999-0.92860837j]
 [-0.31217654-0.31603848j -0.24383863-0.63406316j -0.04569338-0.99550434j
   0.94453467+0.15520717j]
 [-2.82828662+0.j         -0.10452976-1.49670899j -1.8265035 +0.j
  -0.10452976+1.49670899j]
 [-0.31217654+0.31603848j  0.94453467-0.15520717j -0.04569338+0.99550434j
  -0.24383863+0.63406316j]]


### **fft.fftn**
-----------------

#### Function Description
Compute the N-dimensional discrete Fourier Transform.

#### Parameters

* `x`: array_like, input array
* `s`: int or tuple, shape of the output (default None)
* `axes`: int or tuple, axes along which to compute the transform (default None)

#### Returns

* `out`: ndarray, complex transform

#### Examples
```python
import numpy as np
x = np.random.rand(4, 4, 4)
X = np.fft.fftn(x)
print(X)
```


In [9]:
#Interactive Example
import numpy as np
x = np.random.rand(4, 4, 4)
X = np.fft.fftn(x)
print(X)

[[[ 2.91111970e+01+0.j          2.18445863e+00+0.2059687j
    1.84882849e+00+0.j          2.18445863e+00-0.2059687j ]
  [ 1.43244344e+00+0.61358822j  1.62223770e+00-2.89290803j
   -1.09277125e+00+3.06638562j -1.14734287e+00-3.2575078j ]
  [-3.20246331e+00+0.j          4.03213774e-01+2.61798371j
   -1.28917558e-01+0.j          4.03213774e-01-2.61798371j]
  [ 1.43244344e+00-0.61358822j -1.14734287e+00+3.2575078j
   -1.09277125e+00-3.06638562j  1.62223770e+00+2.89290803j]]

 [[-2.34377728e-02-0.15994133j  1.65097347e+00-1.46204245j
   -3.19608813e-01-0.11396537j -3.84152791e+00+1.19502024j]
  [ 1.64536863e+00+3.40947028j -6.52408524e-01-0.11786153j
   -2.81375016e-01+1.44277624j  7.94626652e-01-0.45133904j]
  [-5.20864015e-01-0.16853778j -4.12856688e-02+0.86276214j
   -4.62853065e-01-0.35921932j -1.99625912e+00-0.34130236j]
  [ 1.82974693e+00+2.71036431j  1.65836104e+00+0.05450485j
   -1.19128174e+00-1.27191828j  1.41252929e-01-0.11626812j]]

 [[-3.84008676e+00+0.j          4.32892157e-01

### **rfft2**
-------------

#### Function Description
Compute the 2-dimensional FFT of a real array.

#### Parameters

* `a`: `(M, N)` input array
* `s`: Output shape. If `s` not given, shape of `a` is used.
* `axes`: Axes to perform FFT over.

#### Returns

* `out`: Complex nd-array with `M, N` shape.

#### Examples

```python
import numpy as np

a = np.random.rand(10, 10)
out = np.fft.rfft2(a)
```

In [10]:
#Interactive Example
import numpy as np

a = np.random.rand(10, 10)
out = np.fft.rfft2(a)
print(a)

[[0.04132361 0.97470757 0.30936391 0.37225306 0.17759198 0.87419919
  0.94587544 0.34995139 0.67470379 0.73674403]
 [0.43706535 0.14404895 0.69763164 0.73649637 0.5036577  0.86220461
  0.06247026 0.21667551 0.90878606 0.38383741]
 [0.61767977 0.8789166  0.70058029 0.4081488  0.77429735 0.90304381
  0.9255557  0.05243389 0.01558971 0.74052646]
 [0.33643248 0.39050778 0.47047483 0.65958388 0.99647011 0.23628256
  0.15113449 0.25596892 0.33555398 0.67502199]
 [0.03722341 0.3992667  0.35676902 0.46781269 0.23982992 0.74240027
  0.40992709 0.79463121 0.1011416  0.06723734]
 [0.07466921 0.27048113 0.80688037 0.63862839 0.73563715 0.80782397
  0.50493445 0.07746027 0.92198123 0.16556583]
 [0.34695226 0.43969988 0.89048081 0.34296318 0.64003698 0.47985502
  0.41142037 0.93191904 0.69660813 0.0949378 ]
 [0.99266054 0.54761269 0.08935498 0.53927021 0.35024588 0.12085785
  0.04089951 0.3716816  0.05450713 0.41177222]
 [0.6040373  0.87037251 0.35564872 0.87798817 0.41332513 0.32769776
  0.215039  

### **irfft2**
-------------

#### Function Description
Compute the 2-dimensional inverse FFT of a real array.

#### Parameters

* `a`: `(M, N)` input array
* `s`: Output shape. If `s` not given, shape of `a` is used.
* `axes`: Axes to perform inverse FFT over.

#### Returns

* `out`: Real nd-array with `M, N` shape.

#### Examples

```python
import numpy as np

a = np.random.rand(10, 10)
out = np.fft.irfft2(a)
```

In [11]:
#Interactive Example
import numpy as np

a = np.random.rand(10, 10)
out = np.fft.irfft2(a)
print(out)

[[ 4.91218094e-01  2.84616393e-02  1.35230770e-02 -6.90431472e-03
   7.70667116e-03 -5.01634823e-03 -4.30560548e-02 -3.58759865e-02
  -3.35414397e-02 -1.78040470e-02 -3.35414397e-02 -3.58759865e-02
  -4.30560548e-02 -5.01634823e-03  7.70667116e-03 -6.90431472e-03
   1.35230770e-02  2.84616393e-02]
 [ 6.26119466e-03 -1.87588091e-02 -4.04709508e-02  2.10280065e-02
  -6.65812191e-03 -1.92803002e-02  1.70827302e-02 -1.47392946e-02
   1.01736794e-02  1.35008888e-02  7.43920961e-03 -3.71392129e-02
   1.02317934e-02  3.23862512e-02 -4.83351372e-02 -1.74361320e-02
   3.71529387e-02  3.74994828e-02]
 [ 6.31536997e-03  2.26171736e-02 -3.29059130e-02  3.96977079e-02
   1.72455834e-02  1.18132988e-02 -4.98337791e-02  1.01230733e-02
  -2.10989132e-02  1.01596743e-03 -9.54738679e-03 -7.91377368e-03
   2.02589589e-03 -2.46809009e-02  2.55298249e-02 -4.41777811e-03
   1.63747712e-02 -3.01053635e-02]
 [ 3.74508208e-02 -3.06175163e-02 -2.50569950e-02 -2.10495370e-02
   8.07540256e-03 -7.60494595e-03 -1.

### **hfft**
------------

#### Function Description
Compute the FFT of a Hermitian sequence.

#### Parameters

* `x`: Input array
* `n`: Length of the transformed axis of the output.
* `norm`: Normalization mode.

#### Returns

* `out`: Complex nd-array.

#### Examples

```python
import numpy as np

x = np.random.rand(10)
out = np.fft.hfft(x)
```

In [12]:
#Interactive Example
import numpy as np

x = np.random.rand(10)
out = np.fft.hfft(x)
print(out)

[10.55641149  0.22200875 -1.1429045  -1.02522544  0.48236107 -0.89602155
 -2.36792708 -0.33812006  0.25234331  1.36867417  0.25234331 -0.33812006
 -2.36792708 -0.89602155  0.48236107 -1.02522544 -1.1429045   0.22200875]


### **ihfft**
-------------

#### Function Description
Compute the inverse FFT of a Hermitian sequence.

#### Parameters

* `x`: Input array
* `n`: Length of the transformed axis of the output.
* `norm`: Normalization mode.

#### Returns

* `out`: Real nd-array.

#### Examples

```python
import numpy as np

x = np.random.rand(10)
out = np.fft.ihfft(x)
```

In [13]:
#Interactive Example
import numpy as np

x = np.random.rand(10)
out = np.fft.ihfft(x)
print(out)

[0.26678221-0.j         0.03756382+0.01622948j 0.0821006 +0.00853042j
 0.1060223 +0.02614242j 0.02611152+0.00817166j 0.00374137-0.j        ]


### **rfftfreq**
-------------

#### Function Description
Return the frequencies corresponding to the components of the one-dimensional FFT of a real sequence.

#### Parameters

* `n`: int, Number of data points.
* `d`: float, Sample spacing.

#### Returns

* `f`: An array of length `n` containing the sample frequencies.

#### Examples

```python
import numpy as np

n = 10
d = 0.1
f = np.fft.rfftfreq(n, d)
```

In [14]:
#Interactive Example
import numpy as np

n = 10
d = 0.1
f = np.fft.rfftfreq(n, d)
print(f)

[0. 1. 2. 3. 4. 5.]


### **ifftshift**
-------------

#### Function Description
Shift the zero-frequency component to the edges of the spectrum.

#### Parameters

* `x`: Input array.
* `axes`: Axes to shift.

#### Returns

* `x`: Shifted array.

#### Examples

```python
import numpy as np

x = np.random.rand(10, 10)
x = np.fft.ifftshift(x)
```

In [16]:
#Interactive Example
import numpy as np

x = np.random.rand(10, 10)
x = np.fft.ifftshift(x)
print(x)

[[0.41885903 0.88695869 0.88767036 0.06376144 0.42436464 0.03909701
  0.29380065 0.69551039 0.12437527 0.74121348]
 [0.83979606 0.4377786  0.08450499 0.9642353  0.41921765 0.62914612
  0.5742986  0.35316467 0.24145649 0.72814839]
 [0.12125825 0.1634997  0.18631186 0.13512476 0.24406237 0.43090171
  0.56301446 0.28560774 0.53211386 0.93182888]
 [0.91563659 0.95847922 0.66031804 0.48255048 0.79448593 0.44848054
  0.95960692 0.42417553 0.3750774  0.67243983]
 [0.59481459 0.96561556 0.04476527 0.81357886 0.4306207  0.45769313
  0.52776887 0.49198059 0.940521   0.42664899]
 [0.66626165 0.36836465 0.40300801 0.28672265 0.38016614 0.36096826
  0.41915422 0.21601177 0.22282742 0.59265828]
 [0.72560862 0.70404129 0.4136459  0.34147847 0.26896839 0.49528031
  0.03374585 0.72286857 0.55211247 0.06735885]
 [0.75394523 0.66763229 0.53637655 0.09180692 0.88449244 0.10373825
  0.691253   0.12927151 0.01349504 0.22313705]
 [0.42751406 0.19054847 0.35511714 0.79401931 0.87184374 0.43838641
  0.9888874 