### Cheatsheet for Linear Algebra Functions

#### `inv`
##### Function Description
Compute the inverse of a matrix.

##### Parameters
* `a` : (…, M, M) array_like
 Matrix to be inverted.

##### Returns
* `a_inv` : (…, M, M) ndarray
Inverse of the input matrix `a`.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a)

In [1]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a)
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### `pinv`
##### Function Description
Compute the Moore-Penrose pseudoinverse of a matrix.

##### Parameters
* `a` : (…, M, N) array_like
 Matrix to be pseudoinverted.

##### Returns
* `a_inv` : (…, N, M) ndarray
Moore-Penrose pseudoinverse of the input matrix `a`.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
a_pin = np.linalg.pinv(a)
```

In [2]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
a_pin = np.linalg.pinv(a)
a_pin

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### `matrix_rank`
##### Function Description
Return the rank of a matrix.

##### Parameters
* `M` : array_like
Input matrix.

##### Returns
* `rank` : int
Rank of the input matrix `M`.

##### Examples
```python
import numpy as np
M = np.array([[1, 2], [3, 4]])
rank = np.linalg.matrix_rank(M)
```

In [3]:
# Interactive Example
import numpy as np
M = np.array([[1, 2], [3, 4]])
rank = np.linalg.matrix_rank(M)
rank

np.int64(2)

#### `det`
##### Function Description
Compute the determinant of a matrix.

##### Parameters
* `a` : array_like
Input matrix.

##### Returns
* `det` : float
Determinant of the input matrix `a`.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
det_a = np.linalg.det(a)
```

In [4]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
det_a = np.linalg.det(a)
det_a

np.float64(-2.0000000000000004)

#### `eig`
##### Function Description
Compute the eigenvalues and right eigenvectors of a square matrix.

##### Parameters
* `a` : array_like
Square matrix.

##### Returns
* `w` : ndarray
Eigenvalues.
* `v` : ndarray
Right eigenvectors.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
w, v = np.linalg.eig(a)
```

In [5]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
w, v = np.linalg.eig(a)
w, v

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

#### `eigvals`
##### Function Description
Compute the eigenvalues of a square matrix.

##### Parameters
* `a` : array_like
Square matrix.

##### Returns
* `w` : ndarray
Eigenvalues.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
w = np.linalg.eigvals(a)
```

In [6]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
w = np.linalg.eigvals(a)
w

array([-0.37228132,  5.37228132])

#### `eigvecs`
##### Function Description
Compute the right eigenvectors of a square matrix.

##### Parameters
* `a` : array_like
Square matrix.

##### Returns
* `v` : ndarray
Right eigenvectors.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
v = np.linalg.eigvecs(a)
```

In [16]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
_, v = np.linalg.eig(a)
v

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

#### `solve`
##### Function Description
Solve a linear matrix equation, or system of linear scalar equations.

##### Parameters
* `a` : array_like
Coefficient matrix.
* `b` : array_like
Ordinate or “dependent variable” values.

##### Returns
* `x` : ndarray
Solution to the system.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.solve(a, b)
```

In [7]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.solve(a, b)
x

array([-4. ,  4.5])

#### `lstsq`
##### Function Description
Return the least-squares solution to a linear matrix equation.

##### Parameters
* `a` : array_like
Coefficient matrix.
* `b` : array_like
Ordinate or “dependent variable” values.
* `rcond` : float, optional
Cut-off ratio for small singular values.

##### Returns
* `x` : ndarray
Least-squares solution.
* `residuals` : ndarray
Sums of residuals.
* `rank` : int
Effective rank of `a`.
* `s` : ndarray
Singular values of `a`.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x, res, rank, s = np.linalg.lstsq(a, b)

In [8]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x, res, rank, s = np.linalg.lstsq(a, b, rcond=None)
x, res, rank, s

(array([-4. ,  4.5]),
 array([], dtype=float64),
 np.int32(2),
 array([5.4649857 , 0.36596619]))

#### `qr`
##### Function Description
Compute the QR decomposition of a matrix.

##### Parameters
* `a` : array_like
Matrix to be decomposed.

##### Returns
* `q` : ndarray
Orthogonal matrix.
* `r` : ndarray
Upper triangular matrix.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
q, r = np.linalg.qr(a)

In [9]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
q, r = np.linalg.qr(a)
q, r

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

#### `cholesky`
##### Function Description
Compute the Cholesky decomposition of a matrix.

##### Parameters
* `a` : array_like
 Matrix to be decomposed.

##### Returns
* `c` : ndarray
Cholesky decomposition of `a`.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [2, 5]])
c = np.linalg.cholesky(a)
```

In [10]:
# Interactive Example
a = np.array([[1, 2], [2, 5]])
c = np.linalg.cholesky(a)
c

array([[1., 0.],
       [2., 1.]])

#### `cond`
##### Function Description
Compute the condition number of a matrix.

##### Parameters
* `x` : array_like
Input matrix.

##### Returns
* `c` : float
Condition number of the input matrix.

##### Examples
```python
import numpy as np
x = np.array([[1, 2], [3, 4]])
c = np.linalg.cond(x)
```

In [12]:
# Interactive Example
import numpy as np
x = np.array([[1, 2], [3, 4]])
c = np.linalg.cond(x)
c

np.float64(14.933034373659268)

#### `eigh`
##### Function Description
Compute the eigenvalues and eigenvectors of a Hermitian matrix.

##### Parameters
* `a` : array_like
Hermitian matrix.

##### Returns
* `w` : ndarray
Eigenvalues.
* `v` : ndarray
Eigenvectors.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [2, 5]])
w, v = np.linalg.eigh(a)
```

In [13]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [2, 5]])
w, v = np.linalg.eigh(a)
w, v

(array([0.17157288, 5.82842712]),
 array([[-0.92387953,  0.38268343],
        [ 0.38268343,  0.92387953]]))

#### `eigvalsh`
##### Function Description
Compute the eigenvalues of a Hermitian matrix.

##### Parameters
* `a` : array_like
Hermitian matrix.

##### Returns
* `w` : ndarray
Eigenvalues.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [2, 5]])
w = np.linalg.eigvalsh(a)

In [14]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [2, 5]])
w = np.linalg.eigvalsh(a)
w

array([0.17157288, 5.82842712])

#### `multi_dot`
##### Function Description
Compute the dot product of multiple arrays.

##### Parameters
* `arrays` : sequence of arrays
Arrays to be dotted.

##### Returns
* `result` : ndarray
Dot product of the input arrays.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
result = np.linalg.multi_dot([a, b, c])
```

In [17]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
result = np.linalg.multi_dot([a, b, c])
result

array([[ 413,  454],
       [ 937, 1030]])

#### `norm`
##### Function Description
Compute the norm of a matrix or vector.

##### Parameters
* `x` : array_like
Input matrix or vector.
* `ord` : {non-zero int, inf, -inf, ‘fro’, ‘nuc’}
Norm type.

##### Returns
* `n` : float
Norm of the input matrix or vector.

##### Examples
```python
import numpy as np
x = np.array([[1, 2], [3, 4]])
n = np.linalg.norm(x)
```

In [18]:
# Interactive Example
import numpy as np
x = np.array([[1, 2], [3, 4]])
n = np.linalg.norm(x)
n

np.float64(5.477225575051661)

#### `slogdet`
##### Function Description
Compute the sign and logarithm of the determinant of a matrix.

##### Parameters
* `a` : array_like
Input matrix.

##### Returns
* `sign` : float
Sign of the determinant.
* `logdet` : float
Logarithm of the determinant.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
sign, logdet = np.linalg.slogdet(a)
```

In [19]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
sign, logdet = np.linalg.slogdet(a)
sign, logdet

(np.float64(-1.0), np.float64(0.6931471805599455))

#### `svd`
##### Function Description
Compute the singular value decomposition of a matrix.

##### Parameters
* `a` : array_like
Input matrix.

##### Returns
* `u` : ndarray
Left singular vectors.
* `s` : ndarray
Singular values.
* `vh` : ndarray
Right singular vectors.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
u, s, vh = np.linalg.svd(a)
```

In [20]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
u, s, vh = np.linalg.svd(a)
u, s, vh

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

#### `tensorsolve`

##### Function Description
Solve a tensor equation.

##### Parameters
* `a` : array_like
Coefficient tensor.
* `b` : array_like
Right-hand side tensor.

##### Returns
* `x` : ndarray
Solution to the tensor equation.

##### Examples
```python
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.tensorsolve(a, b)
```

In [22]:
# Interactive Example
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.tensorsolve(a, b)
x

array([-4. ,  4.5])