### Cheatsheet for Masked Array Functions

#### `masked_array`
##### Function Description
Create a masked array.

##### Parameters
* `data` : array_like
Input data.
* `mask` : array_like, optional
Mask array.
* `fill_value` : scalar, optional
Fill value.

##### Returns
* `masked_array` : MaskedArray
Masked array.

##### Examples
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
masked_array = np.ma.masked_array(data, mask)
```

In [2]:
# Interactive Example
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
masked_array = np.ma.masked_array(data, mask)
masked_array

masked_array(data=[--, 2, --, 4, --],
             mask=[ True, False,  True, False,  True],
       fill_value=999999)

#### `masked_where`
##### Function Description
Create a masked array where a condition is True.

##### Parameters
* `condition` : array_like
Condition array.
* `data` : array_like, optional
Input data.

##### Returns
* `masked_array` : MaskedArray
Masked array.

##### Examples
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
condition = np.array([True, False, True, False, True])
masked_array = np.ma.masked_where(condition, data)
```

In [3]:
# Interactive Example
import numpy as np
data = np.array([1, 2, 3, 4, 5])
condition = np.array([True, False, True, False, True])
masked_array = np.ma.masked_where(condition, data)
masked_array

masked_array(data=[--, 2, --, 4, --],
             mask=[ True, False,  True, False,  True],
       fill_value=999999)

#### `masked_equals`
##### Function Description
Create a masked array where values are equal to a specified value.

##### Parameters
* `data` : array_like
Input data.
* `value` : scalar
Value to mask.

##### Returns
* `masked_array` : MaskedArray
Masked array.

##### Examples
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
value = 3
masked_array = np.ma.masked_equals(data, value)
```

In [4]:
# Interactive Example
import numpy as np
data = np.array([1, 2, 3, 4, 5])
value = 3
masked_array = np.ma.masked_equal(data, value)
masked_array


masked_array(data=[1, 2, --, 4, 5],
             mask=[False, False,  True, False, False],
       fill_value=3)

#### `masked_not_equals`
##### Function Description
Create a masked array where values are not equal to a specified value.

##### Parameters
* `data` : array_like
Input data.
* `value` : scalar
Value to mask.

##### Returns
* `masked_array` : MaskedArray
Masked array.

##### Examples
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
value = 3
masked_array = np.ma.masked_not_equals(data, value)
```

In [5]:
# Interactive Example
import numpy as np
data = np.array([1, 2, 3, 4, 5])
value = 3
masked_array = np.ma.masked_not_equal(data, value)
masked_array

masked_array(data=[--, --, 3, --, --],
             mask=[ True,  True, False,  True,  True],
       fill_value=999999)

#### `masked_inside`
##### Function Description
Create a masked array where values are inside a specified range.

##### Parameters
* `data` : array_like
Input data.
* `lower` : scalar
Lower bound of the range.
* `upper` : scalar
Upper bound of the range.

##### Returns
* `masked_array` : MaskedArray
Masked array.

##### Examples
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
lower = 2
upper = 4
masked_array = np.ma.masked_inside(data, lower, upper)
```

In [6]:
# Interactive Example
import numpy as np
data = np.array([1, 2, 3, 4, 5])
lower = 2
upper = 4
masked_array = np.ma.masked_inside(data, lower, upper)
masked_array


masked_array(data=[1, --, --, --, 5],
             mask=[False,  True,  True,  True, False],
       fill_value=999999)

#### `masked_outside`
##### Function Description
Create a masked array where values are outside a specified range.

##### Parameters
* `data` : array_like
Input data.
* `lower` : scalar
Lower bound of the range.
* `upper` : scalar
Upper bound of the range.

##### Returns
* `masked_array` : MaskedArray
Masked array.

##### Examples
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
lower = 2
upper = 4
masked_array = np.ma.masked_outside(data, lower, upper)
```

In [7]:
# Interactive Example
import numpy as np
data = np.array([1, 2, 3, 4, 5])
lower = 2
upper = 4
masked_array = np.ma.masked_outside(data, lower, upper)
masked_array


masked_array(data=[--, 2, 3, 4, --],
             mask=[ True, False, False, False,  True],
       fill_value=999999)

#### `getmask`
##### Function Description
Return the mask of a masked array.

##### Parameters
* `arr` : MaskedArray
Input masked array.

##### Returns
* `mask` : ndarray
Mask of the input masked array.

##### Examples
```python
import numpy as np

arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
mask = np.ma.getmask(arr)
```

In [8]:
# Interactive Example
import numpy as np
arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
mask = np.ma.getmask(arr)
mask

array([ True, False,  True, False,  True])

#### `getmaskarray`
##### Function Description
Return the mask of a masked array as a boolean array.

##### Parameters
* `arr` : MaskedArray
Input masked array.

##### Returns
* `mask` : ndarray
Mask of the input masked array as a boolean array.

##### Examples
```python
import numpy as np

arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
mask = np.ma.getmaskarray(arr)
```

In [9]:
# Interactive Example
import numpy as np
arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
mask = np.ma.getmaskarray(arr)
mask

array([ True, False,  True, False,  True])

#### `getdata`
##### Function Description
Return the data of a masked array.

##### Parameters
* `arr` : MaskedArray
Input masked array.

##### Returns
* `data` : ndarray
Data of the input masked array.

##### Examples
```python
import numpy as np

arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
data = np.ma.getdata(arr)
```

In [11]:
# Interactive Example
import numpy as np
arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
data = np.ma.getdata(arr)
data

array([1, 2, 3, 4, 5])

#### `compressed`
##### Function Description
Return a 1-D iterator over the non-masked elements of a masked array.

##### Parameters
* `arr` : MaskedArray
Input masked array.

##### Returns
* `iterator` : iterator
Iterator over the non-masked elements of the input masked array.

##### Examples
```python
import numpy as np

arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
iterator = np.ma.compressed(arr)
```

In [13]:
# Interactive Example
import numpy as np
arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
iterator = np.ma.compressed(arr)
list(iterator)


[np.int64(2), np.int64(4)]

#### `filled`
##### Function Description
Return a copy of the masked array with the masked elements replaced by a fill value.

##### Parameters
* `arr` : MaskedArray
Input masked array.
* `fill_value` : scalar, optional
Fill value to use.

##### Returns
* `filled_array` : ndarray
Copy of the input masked array with the masked elements replaced by a fill value.

##### Examples
```python
import numpy as np

arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
filled_array = np.ma.filled(arr, fill_value=0)
```

In [15]:
# Interactive Example
import numpy as np
arr = np.ma.array([1, 2, 3, 4, 5], mask=[True, False, True, False, True])
filled_array = np.ma.filled(arr, fill_value=0)
filled_array

array([0, 2, 0, 4, 0])