In [5]:
import re
import numpy as np
import textwrap

In [6]:
np.__version__

'2.1.0.dev0+git20240612.42ed34f'

In [7]:
def generate_commit_message(mod,func,ai_string):
    preamble_string = (f"DOC: AI generated examples for np.{mod}.{func}"
    "\n\n"
    "These examples were created by AI and tested against a dev build of NumPy. AI's reasoning for these examples appears after the skip tags."
    "\n\n"
    "[skip actions] [skip azp] [skip cirrus]")


    # Split the string by newlines
    preamble_lines = preamble_string.splitlines()
    ai_lines = ai_string.splitlines()

    # Combine both lists into one
    lines = preamble_lines + ai_lines

    # Wrap each line separately
    wrapped_lines = [textwrap.fill(line, width=72) for line in lines]

    # Join the wrapped lines with newlines
    wrapped_text = '\n'.join(wrapped_lines)
    return wrapped_text


In [8]:
# Function to execute the commands and get the outputs
def execute_code(code_lines):
    # env = {'np': np}  # Preload the environment with `numpy` imported as `np`
    outputs = []
    for line in code_lines:
        command = line.strip()
        try:
            # Check if the command is an assignment
            if ' = ' in command:
                exec(command) #, env)
                outputs.append(None)  # No output for assignment commands
            else:
                result = eval(command) #, env)  # Evaluate the command if it's not an assignment
                outputs.append(result)
        except Exception as e:
            outputs.append(f"Error: {e}")
    return outputs

def format_output(output):
    if isinstance(output, np.ndarray):
        return repr(output)
    return repr(output)

def evaluated_code_block(text):
    # Trim white space at the start of each line
    text = '\n'.join(line.lstrip() for line in text.split('\n'))

    # Extract the code blocks
    code_lines = re.findall(r'>>> (.*)', text)
    outputs = execute_code(code_lines)

    # Create the new text with actual outputs
    new_text_lines = []
    output_idx = 0
    for line in text.split('\n'):
        if line.startswith('>>>'):
            new_text_lines.append(line)
            if output_idx < len(outputs):
                output = outputs[output_idx]
                output_idx += 1
                if output is not None:  # Skip None outputs
                    output_str = format_output(output)
                    # Split output into multiple lines if necessary
                    output_lines = output_str.split('\n')
                    new_text_lines.extend(output_lines)

    # Add 4 spaces to the start of each line
    new_text_lines = ['    ' + line for line in new_text_lines]

    # Join the lines back into a single string
    new_text = '\n'.join(new_text_lines)
    return new_text


Outer

In [9]:
# Start cell with a comment to avoid Jupyter bug.
text = """
    Simple outer product:

    >>> a = np.array([1, 2, 3])
    >>> b = np.array([4, 5, 6])
    >>> np.linalg.outer(a, b)
    array([[ 4,  5,  6],
           [ 8, 10, 12],
           [12, 15, 18]])

    Outer product with negative numbers:

    >>> a = np.array([-1, 2, 3])
    >>> b = np.array([4, -5, 6])
    >>> np.linalg.outer(a, b)
    array([[ -4,   5,  6],
           [  8, -10,  12],
           [ 12, -15,  18]])
"""

correct_code = evaluated_code_block(text)
print(correct_code)


    >>> a = np.array([1, 2, 3])
    >>> b = np.array([4, 5, 6])
    >>> np.linalg.outer(a, b)
    array([[ 4,  5,  6],
           [ 8, 10, 12],
           [12, 15, 18]])
    >>> a = np.array([-1, 2, 3])
    >>> b = np.array([4, -5, 6])
    >>> np.linalg.outer(a, b)
    array([[ -4,   5,  -6],
           [  8, -10,  12],
           [ 12, -15,  18]])


In [10]:

mod = 'linalg'
func = 'outer'
ai_string = """
I decided to add these examples because they demonstrate the basic usage of the np.linalg.outer function and show how it handles positive and negative numbers. The first example is a simple demonstration of the outer product, while the second example shows that the function works correctly with negative numbers.

I stopped adding examples because the existing examples cover the basic usage of the function, and additional examples would likely be redundant or too specific. The function is relatively simple, and the existing examples provide a good understanding of its behavior. Adding more examples would not significantly improve the documentation.
"""

print(generate_commit_message(mod,func,ai_string))


DOC: AI generated examples for np.linalg.outer

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add these examples because they demonstrate the basic usage
of the np.linalg.outer function and show how it handles positive and
negative numbers. The first example is a simple demonstration of the
outer product, while the second example shows that the function works
correctly with negative numbers.

I stopped adding examples because the existing examples cover the basic
usage of the function, and additional examples would likely be redundant
or too specific. The function is relatively simple, and the existing
examples provide a good understanding of its behavior. Adding more
examples would not significantly improve the documentation.


eig

In [48]:
#Start cell with comment to avoid Jupyter bug
from numpy import linalg as LA
text = """
    Be careful when the matrix has repeated eigenvalues.

    >>> A = np.array([[2, 1], [0, 2]])
    >>> eigenvalues, eigenvectors = np.linalg.eig(A)
    >>> eigenvalues
    array([2., 1.])
    >>> eigenvectors
    array([[0.70710678, 0.70710678],
           [0.70710678, -0.70710678]])
    >>> A @ eigenvectors[:,0]
    >>> A @ eigenvectors[:,1]
    
"""

correct_code = evaluated_code_block(text)
print(correct_code)


    >>> A = np.array([[2, 1], [0, 2]])
    >>> eigenvalues, eigenvectors = np.linalg.eig(A)
    >>> eigenvalues
    array([2., 2.])
    >>> eigenvectors
    array([[ 1.0000000e+00, -1.0000000e+00],
           [ 0.0000000e+00,  4.4408921e-16]])
    >>> A @ eigenvectors[:,0]
    array([2., 0.])
    >>> A @ eigenvectors[:,1]
    array([-2.0000000e+00,  8.8817842e-16])


In [44]:
func = 'eig'
ai_string = """
I decided to add an example to illustrate the case where the matrix has repeated eigenvalues. This is an important scenario that may not be immediately clear to users, and providing an example can help clarify the behavior of the `eig` function in this case.

I stopped after adding one example because the existing examples already cover a wide range of scenarios, including real and complex matrices, Hermitian matrices, and the importance of considering round-off error. The additional example I provided helps to further illustrate the behavior of the `eig` function, but it is not necessary to add more examples at this point. The existing examples, along with the new one, provide a comprehensive understanding of the `eig` function. If more examples were needed, they would likely involve more complex or edge cases, such as non-square matrices or matrices with very large or very small eigenvalues. However, these cases are unlikely to be common use cases for the `eig` function, and the existing examples are sufficient for most users.
"""

print(generate_commit_message(mod,func,ai_string))



DOC: AI generated examples for np.linalg.eig

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add an example to illustrate the case where the matrix has
repeated eigenvalues. This is an important scenario that may not be
immediately clear to users, and providing an example can help clarify
the behavior of the `eig` function in this case.

I stopped after adding one example because the existing examples already
cover a wide range of scenarios, including real and complex matrices,
Hermitian matrices, and the importance of considering round-off error.
The additional example I provided helps to further illustrate the
behavior of the `eig` function, but it is not necessary to add more
examples at this point. The existing examples, along with the new one,
provide a comprehensive understanding of the `eig` function. If more
examples were needed, they

svd

In [53]:
#Start cell with comment to avoid Jupyter bug
text = """
    >>> rng = np.random.default_rng()

    Using hermitian flag:

    >>> a = rng.normal(size=(9, 9)) + 1j*rng.normal(size=(9, 9))
    >>> U, S, Vh = np.linalg.svd(a, hermitian=True)
    >>> U.shape, S.shape, Vh.shape
    ((9, 9), (9,), (9, 9))
    >>> np.allclose(a, np.dot(U, np.dot(np.diag(S), Vh)))
    True

    Using hermitian flag:

    >>> a = rng.normal(size=(9, 9)) + 1j*rng.normal(size=(9, 9))
    >>> U, S, Vh = np.linalg.svd(a, hermitian=True)
    >>> U.shape, S.shape, Vh.shape
    ((9, 9), (9,), (9, 9))
    >>> np.allclose(a, np.dot(U[:, :9] * S, Vh))
    True
    >>> smat = np.zeros((9, 9), dtype=complex)
    >>> smat[:9, :9] = np.diag(S)
    >>> np.allclose(a, np.dot(U, np.dot(smat, Vh)))
    True


    >>> a = rng.normal(size=(9, 9)) + 1j*rng.normal(size=(9, 9))
    >>> herm = a.T.conj() @ a
    >>> U, S, Vh = np.linalg.svd(herm, hermitian=True)
    >>> U.shape, S.shape, Vh.shape
    ((9, 9), (9,), (9, 9))
    >>> np.allclose(herm, U @ np.diag(S) @ Vh)
    False

"""

correct_code = evaluated_code_block(text)
print(correct_code)


    >>> rng = np.random.default_rng()
    >>> a = rng.normal(size=(9, 9)) + 1j*rng.normal(size=(9, 9))
    >>> U, S, Vh = np.linalg.svd(a, hermitian=True)
    >>> U.shape, S.shape, Vh.shape
    ((9, 9), (9,), (9, 9))
    >>> np.allclose(a, np.dot(U, np.dot(np.diag(S), Vh)))
    False
    >>> a = rng.normal(size=(9, 9)) + 1j*rng.normal(size=(9, 9))
    >>> U, S, Vh = np.linalg.svd(a, hermitian=True)
    >>> U.shape, S.shape, Vh.shape
    ((9, 9), (9,), (9, 9))
    >>> np.allclose(a, np.dot(U[:, :9] * S, Vh))
    False
    >>> smat = np.zeros((9, 9), dtype=complex)
    >>> smat[:9, :9] = np.diag(S)
    >>> np.allclose(a, np.dot(U, np.dot(smat, Vh)))
    False
    >>> a = rng.normal(size=(9, 9)) + 1j*rng.normal(size=(9, 9))
    >>> herm = a.T.conj() @ a
    >>> U, S, Vh = np.linalg.svd(herm, hermitian=True)
    >>> U.shape, S.shape, Vh.shape
    ((9, 9), (9,), (9, 9))
    >>> np.allclose(herm, U @ np.diag(S) @ Vh)
    True


In [14]:
func = 'svd'
ai_string = """
I decided to add an example for using the `hermitian` flag, which demonstrates how to use this feature to take advantage of the symmetry of the input matrix. This example shows how to use the `hermitian` flag to improve the efficiency of the SVD computation when the input matrix is Hermitian (symmetric if real-valued).

I stopped adding examples because the existing examples already cover the main use cases of the `svd` function, including 2D and 4D cases, full and reduced SVD, and reconstruction of the original matrix. The additional example I added provides further insight into the usage of the `hermitian` flag, which is an important feature of the `svd` function. Adding more examples would likely be redundant and may make the documentation harder to read. Instead, it's better to focus on making the existing examples clear and concise.
"""

print(generate_commit_message(mod,func,ai_string))



DOC: AI generated examples for np.linalg.svd

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add an example for using the `hermitian` flag, which
demonstrates how to use this feature to take advantage of the symmetry
of the input matrix. This example shows how to use the `hermitian` flag
to improve the efficiency of the SVD computation when the input matrix
is Hermitian (symmetric if real-valued).

I stopped adding examples because the existing examples already cover
the main use cases of the `svd` function, including 2D and 4D cases,
full and reduced SVD, and reconstruction of the original matrix. The
additional example I added provides further insight into the usage of
the `hermitian` flag, which is an important feature of the `svd`
function. Adding more examples would likely be redundant and may make
the documentation harder to read. Inste

svdvals

In [54]:
func = 'svdvals'

text = """
    Examples
    --------
    Single matrix singular values:
    >>> rng = np.random.default_rng()
    >>> x = rng.random(size=(3, 3))
    >>> s = np.linalg.svdvals(x)
    >>> s.shape
    (3,)
    Multiple matrix singular values:
    >>> x = rng.random(size=(2, 3, 3))
    >>> s = np.linalg.svdvals(x)
    >>> s.shape
    (2, 3)
    Real matrix singular values:
    >>> x = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
    >>> s = np.linalg.svdvals(x)
    >>> s
    array([3., 2., 1.])
"""

ai_string = """
I decided to add these examples because they illustrate different use cases of the `svdvals` function. The first example shows how to compute the singular values of a single matrix. The second example demonstrates how to compute the singular values of multiple matrices stacked together. The third example provides a simple, intuitive example of computing singular values of a real matrix.
"""

In [55]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> rng = np.random.default_rng()
    >>> x = rng.random(size=(3, 3))
    >>> s = np.linalg.svdvals(x)
    >>> s.shape
    (3,)
    >>> x = rng.random(size=(2, 3, 3))
    >>> s = np.linalg.svdvals(x)
    >>> s.shape
    (2, 3)
    >>> x = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
    >>> s = np.linalg.svdvals(x)
    >>> s
    array([3., 2., 1.])


In [17]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.svdvals

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add these examples because they illustrate different use
cases of the `svdvals` function. The first example shows how to compute
the singular values of a single matrix. The second example demonstrates
how to compute the singular values of multiple matrices stacked
together. The third example provides a simple, intuitive example of
computing singular values of a real matrix.


matrix_rank

In [18]:
func = 'matrix_rank'
from numpy.linalg import matrix_rank
text = """
    >>> matrix_rank(np.eye(4)) # Full rank matrix
    4
    >>> I=np.eye(4); I[-1,-1] = 0. # rank deficient matrix
    >>> matrix_rank(I)
    3
    >>> matrix_rank(np.ones((4,))) # 1 dimension - rank 1 unless all 0
    1
    >>> matrix_rank(np.zeros((4,)))
    0

    Matrix with complex numbers:
    
    >>> A = np.array([[1+1j, 2+2j], [3+3j, 4+4j]])
    >>> matrix_rank(A)
    2
"""

ai_string = """
I decided to add an example with a complex matrix because the function can handle complex input arrays, but there was no example showing this. This example demonstrates that the function works correctly with complex numbers.
"""

In [19]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> matrix_rank(np.eye(4)) # Full rank matrix
    np.int64(4)
    >>> I=np.eye(4); I[-1,-1] = 0. # rank deficient matrix
    >>> matrix_rank(I)
    np.int64(3)
    >>> matrix_rank(np.ones((4,))) # 1 dimension - rank 1 unless all 0
    1
    >>> matrix_rank(np.zeros((4,)))
    0
    >>> A = np.array([[1+1j, 2+2j], [3+3j, 4+4j]])
    >>> matrix_rank(A)
    np.int64(2)


In [20]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.matrix_rank

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add an example with a complex matrix because the function
can handle complex input arrays, but there was no example showing this.
This example demonstrates that the function works correctly with complex
numbers.


In [21]:
np.linalg.matrix_rank(np.eye(4)) # Full rank matrix

np.int64(4)

In [22]:
np.linalg.matrix_rank(np.ones((4,))) # 1 dimension - rank 1 unless all 0

1

det

In [23]:
func = 'det'

text = """
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary

    Computing determinants for a stack of matrices:

    >>> a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
    >>> a.shape
    (3, 2, 2)
    >>> np.linalg.det(a)
    array([-2., -3., -8.])


    Zero determinant for a singular matrix:
    >>> a = np.array([[1, 0], [0, 0]])
    >>> np.linalg.det(a)
    0.0 # may vary
"""

ai_string = """
I decided to add an example to show the case where the input matrix is singular (i.e., its determinant is zero). This is an important edge case that users should be aware of.
"""

In [24]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    np.float64(-2.0000000000000004)
    >>> a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
    >>> a.shape
    (3, 2, 2)
    >>> np.linalg.det(a)
    array([-2., -3., -8.])
    >>> a = np.array([[1, 0], [0, 0]])
    >>> np.linalg.det(a)
    np.float64(0.0)


In [25]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.det

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add an example to show the case where the input matrix is
singular (i.e., its determinant is zero). This is an important edge case
that users should be aware of.


multi_dot

In [26]:
func = 'multi_dot'
from numpy.linalg import multi_dot

text = """

    >>> A = np.random.random((10000, 100))
    >>> B = np.random.random((100, 1000))
    >>> C = np.random.random((1000, 5))
    >>> D = np.random.random((5, 333))
    >>> _ = multi_dot([A, B, C, D])

    Using multi_dot with 1-D arrays:
    >>> a = np.random.random((10,))
    >>> b = np.random.random((10,))
    >>> c = np.random.random((10,))
    >>> d = np.random.random((10,))
    >>>
    >>> _ = multi_dot([a, b, c, d])
"""

ai_string = """
I decided to add an example to show how `multi_dot` can be used with 1-D arrays, as this is a specific case mentioned in the documentation. This example helps to clarify how `multi_dot` treats 1-D arrays as row or column vectors.
"""

Example is trash. Delete it.

In [27]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> A = np.random.random((10000, 100))
    >>> B = np.random.random((100, 1000))
    >>> C = np.random.random((1000, 5))
    >>> D = np.random.random((5, 333))
    >>> _ = multi_dot([A, B, C, D])
    >>> a = np.random.random((10,))
    >>> b = np.random.random((10,))
    >>> c = np.random.random((10,))
    >>> d = np.random.random((10,))
    >>>
    'Error: 1-dimensional array given. Array must be two-dimensional'
    >>> _ = multi_dot([a, b, c, d])


In [28]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.multi_dot

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add an example to show how `multi_dot` can be used with 1-D
arrays, as this is a specific case mentioned in the documentation. This
example helps to clarify how `multi_dot` treats 1-D arrays as row or
column vectors.


trace

In [69]:
func = 'trace'

text = """
    Examples
    --------
    Computing the main diagonal trace:
    >>> x = np.array([[1, 2], [3, 4]])
    >>> np.linalg.trace(x)
    5
    Computing the trace of a stack of matrices:
    >>> x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    >>> np.linalg.trace(x)
    array([5, 13])
    Computing the trace of a 3D array:
    >>> x = np.arange(16).reshape((2,2,2,2))
    >>> np.linalg.trace(x)
    array([[ 5, 13], [29, 41]])
    >>> x
    Computing the trace with a specific data type:
    >>> x = np.array([[1, 2], [3, 4]])
    >>> np.linalg.trace(x, dtype=float)
    5.0    
"""

ai_string = """
I decided to add these examples because they demonstrate different use cases of the `np.linalg.trace` function, such as computing the main diagonal trace, the trace of a stack of matrices, the trace of a 3D array, and the trace with a specific data type. These examples help to illustrate the flexibility and functionality of the `np.linalg.trace` function.
"""

In [70]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> x = np.array([[1, 2], [3, 4]])
    >>> np.linalg.trace(x)
    np.int64(5)
    >>> x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    >>> np.linalg.trace(x)
    array([ 5, 13])
    >>> x = np.arange(16).reshape((2,2,2,2))
    >>> np.linalg.trace(x)
    array([[ 3, 11],
           [19, 27]])
    >>> x
    array([[[[ 0,  1],
             [ 2,  3]],
    
            [[ 4,  5],
             [ 6,  7]]],
    
    
           [[[ 8,  9],
             [10, 11]],
    
            [[12, 13],
             [14, 15]]]])
    >>> x = np.array([[1, 2], [3, 4]])
    >>> np.linalg.trace(x, dtype=float)
    np.float64(5.0)


In [68]:
    >>> x = np.arange(16).reshape((2,2,2,2))
    >>> np.linalg.trace(x)
x


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [32]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.trace

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add these examples because they demonstrate different use
cases of the `np.linalg.trace` function, such as computing the main
diagonal trace, the trace of a stack of matrices, the trace of a 3D
array, and the trace with a specific data type. These examples help to
illustrate the flexibility and functionality of the `np.linalg.trace`
function.


matmul

In [33]:
func = 'matmul'

text = """
    Examples
    --------
    Matrix multiplication:
    >>> np.linalg.matmul([[1, 2], [3, 4]], [[5, 6], [7, 8]])
    [[19 22],
    [43 50]]
    Matrix-vector multiplication:
    >>> np.linalg.matmul([[1, 2], [3, 4]], [5, 6])
    [17 39]
    Vector-vector multiplication:
    >>> np.linalg.matmul([1, 2], [3, 4])
    11
    Matrix-matrix multiplication with 3D arrays:
    >>> x1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    >>> x2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
    >>> np.linalg.matmul(x1, x2)
    [[[57 64],
    [79  88]],
    [[165 184],
    [197 224]]]
"""

ai_string = """
I decided to add these examples because they demonstrate different use cases of the `matmul` function, such as matrix-matrix multiplication, matrix-vector multiplication, and vector-vector multiplication. I also added an example with 3D arrays to show how the function handles higher-dimensional inputs.
"""

In [34]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> np.linalg.matmul([[1, 2], [3, 4]], [[5, 6], [7, 8]])
    array([[19, 22],
           [43, 50]])
    >>> np.linalg.matmul([[1, 2], [3, 4]], [5, 6])
    array([17, 39])
    >>> np.linalg.matmul([1, 2], [3, 4])
    np.int64(11)
    >>> x1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    >>> x2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
    >>> np.linalg.matmul(x1, x2)
    array([[[ 31,  34],
            [ 71,  78]],
    
           [[155, 166],
            [211, 226]]])


In [35]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.matmul

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add these examples because they demonstrate different use
cases of the `matmul` function, such as matrix-matrix multiplication,
matrix-vector multiplication, and vector-vector multiplication. I also
added an example with 3D arrays to show how the function handles higher-
dimensional inputs.


vecdot

In [36]:
func = 'vecdot'

text = """
    Examples
    --------

    Dot product of two 1-D arrays:

    >>> a = np.array([1, 2, 3])
    >>> b = np.array([4, 5, 6])
    >>> np.linalg.vecdot(a, b)
    32

    Dot product of two 2-D arrays along the last axis:

    >>> a = np.array([[1, 2], [3, 4]])
    >>> b = np.array([[5, 6], [7, 8]])
    >>> np.linalg.vecdot(a, b, axis=-1)
    array([17, 53])

    Dot product of two complex vectors:

    >>> a = np.array([1 + 2j, 3 + 4j])
    >>> b = np.array([5 + 6j, 7 + 8j])
    >>> np.linalg.vecdot(a, b)
    (26+64j)

"""

ai_string = """
I decided to add these examples because they demonstrate different use cases of the `vecdot` function, such as computing the dot product of 1-D arrays, 2-D arrays along a specific axis, and complex vectors. These examples will help users understand how to use the function in various scenarios.
"""

In [37]:
correct_code = evaluated_code_block(text)
print(correct_code)

    >>> a = np.array([1, 2, 3])
    >>> b = np.array([4, 5, 6])
    >>> np.linalg.vecdot(a, b)
    np.int64(32)
    >>> a = np.array([[1, 2], [3, 4]])
    >>> b = np.array([[5, 6], [7, 8]])
    >>> np.linalg.vecdot(a, b, axis=-1)
    array([17, 53])
    >>> a = np.array([1 + 2j, 3 + 4j])
    >>> b = np.array([5 + 6j, 7 + 8j])
    >>> np.linalg.vecdot(a, b)
    np.complex128(70-8j)


In [38]:
print(generate_commit_message(mod,func,ai_string))

DOC: AI generated examples for np.linalg.vecdot

These examples were created by AI and tested against a dev build of
NumPy. AI's reasoning for these examples appears after the skip tags.

[skip actions] [skip azp] [skip cirrus]

I decided to add these examples because they demonstrate different use
cases of the `vecdot` function, such as computing the dot product of 1-D
arrays, 2-D arrays along a specific axis, and complex vectors. These
examples will help users understand how to use the function in various
scenarios.


In [73]:
message = """DOC: AI generated examples for multiple functions in linalg

These examples were originally created by AI, and then adapted and updated as needed through human review.

The functions with new examples are `outer`, `eig`, `svd`, `svdvals`, `matrix_rank`, `trace`, `matmul`, `vecdot`.

[skip actions] [skip azp] [skip cirrus]
"""
# Split the string by newlines
lines = message.splitlines()

# Wrap each line separately
wrapped_lines = [textwrap.fill(line, width=72) for line in lines]

# Join the wrapped lines with newlines
wrapped_text = '\n'.join(wrapped_lines)
print(wrapped_text)


DOC: AI generated examples for multiple functions in linalg

These examples were originally created by AI, and then adapted and
updated as needed through human review.

The functions with new examples are `outer`, `eig`, `svd`, `svdvals`,
`matrix_rank`, `trace`, `matmul`, `vecdot`.

[skip actions] [skip azp] [skip cirrus]
