In [1]:
import re
import numpy as np

In [2]:
# Function to execute the commands and get the outputs
def execute_code(code_lines):
    env = {'np': np}  # Preload the environment with `numpy` imported as `np`
    outputs = []
    for line in code_lines:
        command = line.strip()
        try:
            # Check if the command is an assignment
            if '=' in command:
                exec(command, env)
                outputs.append(None)  # No output for assignment commands
            else:
                result = eval(command, env)  # Evaluate the command if it's not an assignment
                outputs.append(result)
        except Exception as e:
            outputs.append(f"Error: {e}")
    return outputs

def format_output(output):
    if isinstance(output, np.ndarray):
        return repr(output)
    return repr(output)

def evaluated_code_block(text):
    # Trim white space at the start of each line
    text = '\n'.join(line.lstrip() for line in text.split('\n'))

    # Extract the code blocks
    code_lines = re.findall(r'>>> (.*)', text)
    outputs = execute_code(code_lines)

    # Create the new text with actual outputs
    new_text_lines = []
    output_idx = 0
    for line in text.split('\n'):
        if line.startswith('>>>'):
            new_text_lines.append(line)
            if output_idx < len(outputs):
                output = outputs[output_idx]
                output_idx += 1
                if output is not None:  # Skip None outputs
                    output_str = format_output(output)
                    # Split output into multiple lines if necessary
                    output_lines = output_str.split('\n')
                    new_text_lines.extend(output_lines)

    # Add 4 spaces to the start of each line
    new_text_lines = ['    ' + line for line in new_text_lines]

    # Join the lines back into a single string
    new_text = '\n'.join(new_text_lines)
    return new_text


In [3]:
# Cells must start with a comment, see https://github.com/jupyterlab/jupyterlab/issues/16483
text = """
>>> a = np.array([-1, 2, 3])
>>> b = np.array([4, -5, 6])
>>> np.linalg.outer(a, b)
array([[ -4,   5,  6],
       [  8, -10,  12],
       [ 12, -15,  18]])
"""

correct_code = evaluated_code_block(text)
print(correct_code)

    >>> a = np.array([-1, 2, 3])
    >>> b = np.array([4, -5, 6])
    >>> np.linalg.outer(a, b)
    array([[ -4,   5,  -6],
           [  8, -10,  12],
           [ 12, -15,  18]])


In [4]:
# Comment
text = """
>>> eigenvalues, eigenvectors = np.linalg.eig(np.array([[2, 1], [1, 1]]))
>>> eigenvalues
array([2., 1.])
>>> eigenvectors
array([[0.70710678, 0.70710678],
[0.70710678, -0.70710678]])
"""

# Process the text and print the output
new_text = evaluated_code_block(text)
print(new_text)


    >>> eigenvalues, eigenvectors = np.linalg.eig(np.array([[2, 1], [1, 1]]))
    >>> eigenvalues
    array([2.61803399, 0.38196601])
    >>> eigenvectors
    array([[ 0.85065081, -0.52573111],
           [ 0.52573111,  0.85065081]])
